import type { User } from "./validations";

export const users: User[] = [
  {
    id: "LO00001",
    fullname: "Mr. David Nguyen",
    username: "davidnguyen",
    avatar: "https://avatar.iran.liara.run/public",
    phoneNumber: "(322) 243-3452",
    email: "david.nguyen@gmail.com",
    type: "Loan Officer",
    experience: "5 years",
    status: "active",
  },
  {
    id: "UW00001",
    fullname: "Ms. Jennie Pink",
    username: "jenniepink",
    avatar: "https://avatar.iran.liara.run/public",
    phoneNumber: "(322) 243-3452",
    email: "jenniepink@gmail.com",
    type: "Underwriter",
    experience: "5 years",
    status: "active",
  },
  {
    id: "LP00001",
    fullname: "Mr. Pep Guardiola",
    username: "pepguardiola",
    avatar: "https://avatar.iran.liara.run/public",
    phoneNumber: "(322) 243-3452",
    email: "pepguardiola@gmail.com",
    type: "Loan Processor",
    experience: "5 years",
    status: "active",
  },
  {
    id: "AD00001",
    fullname: "Mr. Bruno Mar",
    username: "brunomars",
    avatar: "https://avatar.iran.liara.run/public",
    phoneNumber: "(322) 243-3452",
    email: "brunomors@gmail.com",
    type: "Admin",
    experience: "5 years",
    status: "active",
  },
  {
    id: "ME00001",
    fullname: "Mr. David Beckham",
    username: "davidbeckham",
    avatar: "https://avatar.iran.liara.run/public",
    phoneNumber: "(322) 243-3452",
    email: "davidbeckham@gmail.com",
    type: "Member",
    experience: "5 years",
    status: "active",
  },
];
